namespace SR.Data.Seed;

public static class Preprocess
{
    public static List<string> Occupations { get; } = new List<string>
    {
        "Farmer", "Carpenter", "Doctor", "Nurse", "Lab Technician", "Teacher", "Dressmaker", "Painter",
        "Receptionist"
    };

    public static List<string> FemaleNames { get; } = new List<string>
    {
        "Susan",
        "Christine",
        "Margaret",
        "Judith",
        "Jennifer",
        "Karen",
        "Patricia",
        "Mary",
        "Linda",
        "Barbara",
        "Elizabeth",
        "Robyn",
        "Wendy",
        "Helen",
        "Heather",
        "Lynette",
        "Anne",
        "Sandra",
        "Diane",
        "Carol",
        "Pamela",
        "Janice",
        "Janet",
        "Suzanne",
        "Raewyn",
        "Sharon",
        "Dianne",
        "Julie",
        "Rosemary",
        "Deborah",
        "Pauline",
        "Alison",
        "Kathleen",
        "Denise",
        "Lorraine",
        "Catherine",
        "Yvonne",
        "Marie",
        "Ann",
        "Beverley",
        "Lesley",
        "Shirley",
        "Colleen",
        "Annette",
        "Marilyn",
        "Maureen",
        "Glenda",
        "Jane",
        "Jillian",
        "Sheryl",
        "Gail",
        "Lynda",
        "Brenda",
        "Jacqueline",
        "Kay",
        "Carolyn",
        "Marion",
        "Maria",
        "Cheryl",
        "Donna",
        "Kathryn",
        "Vicki",
        "Jeanette",
        "Jan",
        "Gillian",
        "Sally",
        "Ruth",
        "Lynne",
        "Jocelyn",
        "Jill",
        "Joanne",
        "Maree",
        "Frances",
        "Valerie",
        "Elaine",
        "Dorothy",
        "Glenys",
        "Shona",
        "Adrienne",
        "Irene",
        "Joy",
        "Angela",
        "Lois",
        "Paula",
        "Vivienne",
        "Bronwyn",
        "Fiona",
        "Louise",
        "Stephanie",
        "Debra",
        "Christina",
        "Ngaire",
        "Jean",
        "Diana",
        "Claire",
        "Lynnette",
        "Joan",
        "Penelope",
        "Gloria",
        "Katherine"
    };

    public static List<string> MaleNames { get; } = new List<string>
    {
        "John",
        "David",
        "Peter",
        "Michael",
        "Robert",
        "Paul",
        "Stephen",
        "Kevin",
        "Christopher",
        "Brian",
        "William",
        "Ian",
        "Mark",
        "Richard",
        "Alan",
        "Bruce",
        "Murray",
        "Graeme",
        "Wayne",
        "James",
        "Gary",
        "Anthony",
        "Graham",
        "Philip",
        "Barry",
        "Colin",
        "Trevor",
        "Kenneth",
        "Ross",
        "Grant",
        "Geoffrey",
        "Raymond",
        "Keith",
        "Allan",
        "Donald",
        "Ronald",
        "Roger",
        "Steven",
        "Gregory",
        "Neil",
        "Andrew",
        "Warren",
        "Garry",
        "Russell",
        "Thomas",
        "Dennis",
        "Phillip",
        "Stuart",
        "Douglas",
        "George",
        "Robin",
        "Leslie",
        "Malcolm",
        "Gordon",
        "Edward",
        "Neville",
        "Terence",
        "Martin",
        "Charles",
        "Patrick",
        "Timothy",
        "Lindsay",
        "Noel",
        "Rex",
        "Kerry",
        "Joseph",
        "Brent",
        "Craig",
        "Jeffrey",
        "Gavin",
        "Rodney",
        "Nigel",
        "Alexander",
        "Bryan",
        "Owen",
        "Tony",
        "Eric",
        "Lawrence",
        "Glenn",
        "Arthur",
        "Bernard",
        "Denis",
        "Ivan",
        "Francis",
        "Mervyn",
        "Henry",
        "Gerard",
        "Norman",
        "Derek",
        "Desmond",
        "Simon",
        "Maurice",
        "Nicholas",
        "Lance",
        "Brett",
        "Daniel",
        "Frederick",
        "Roy",
        "Stewart",
        "Kelvin"
    };

    public static List<string> Cities { get; } = new List<string>
    {
        "Accra",
        "Kumasi",
        "Tamale",
        "Sekondi-Takoradi",
        "Ashiaman",
        "Sunyani",
        "Cape Coast",
        "Obuasi",
        "Teshie",
        "Tema",
        "Madina",
        "Koforidua",
        "Wa",
        "Techiman",
        "Ho",
        "Nungua",
        "Lashibi",
        "Dome",
        "Tema New Town",
        "Gbawe",
        "Oduponkpehe",
        "Ejura",
        "Taifa",
        "Bawku",
        "Aflao",
        "Agona Swedru",
        "Bolgatanga",
        "Tafo",
        "Berekum",
        "Nkawkaw",
        "Akim Oda",
        "Winneba",
        "Hohoe",
        "Yendi",
        "Suhum",
        "Kintapo",
        "Adenta East",
        "Nsawam",
        "Mampong",
        "Konongo",
        "Asamankese",
        "Wenchi",
        "Savelugu",
        "Agogo",
        "Anloga",
        "Prestea",
        "Effiakuma",
        "Tarkwa",
        "Elmina",
        "Dunkwa-on-Offin",
        "Begoro",
        "Kpandu",
        "Kintampo",
        "Navrongo",
        "Axim",
        "Apam",
        "Salaga",
        "Saltpond",
        "Akwatia",
        "Shama",
        "Keta",
        "Nyakrom",
        "Bibiani",
        "Somanya",
        "Foso",
        "Aburi",
        "Mumford",
        "Bechem",
        "Duayaw Nkwanta",
        "Kade",
        "Anomabu",
        "Akropong",
        "Kete-Krachi",
        "Kibi",
        "Kpandae",
        "Mpraeso",
        "Akim Swedru",
        "Aboso",
        "Bekwai"
    };

    public static List<string> Surnames { get; } = new List<string>
    {
        "AASUOR", "ADAMA", "AGUREE", "AKOJE", "ALHASSAN", "ANDOH", "ANGFAARA", "ANGKO", "ANGKYIIRINAA",
        "ANG-NAPONG", "ANGTUOKUU", "ANNI-EKYE", "ANZANE", "ASAASIBA", "AWULIBO", "AYI", "AYINDOLMA", "BAAGIRO",
        "BABALANGNANUO", "BABAREMAKURONG", "BADA", "BADIKUE", "BAKANG", "BANANTIRE", "BASHIRU", "BA-UU", "BAVENG",
        "BAVUURNYE", "BAWATIEREKORO", "BAYELEDIRE", "BAYOR", "BAYUGO", "BAYUO", "BAZELYE", "BODIEU", "BOKONOBA",
        "BOMBAARE", "BONDINOBA", "BONDONG", "BONGARE", "BONGO", "BONYINAA", "BOOLAAR", "BOOLANGPUO", "BOOWUO",
        "BORSUWIE", "BRAIMAH", "BUROR", "CANCHEON", "DAAH", "DAFAA", "DAHAN", "DAKURA", "DAKURAH", "DANKURE",
        "DAPILAH", "DAR", "DARI", "DEKO-ANG", "DERIGUBAH", "DERY", "DIAMUKA", "DIEGOL", "DIYAAH", "DONGBANYUURO",
        "DONGDEME", "DONGKARAA", "DONGSEGEE", "DONGZIE", "DOODAA", "DORNYUOR", "DORSAA", "DORSAAH", "DORZIE",
        "DOZONG", "DRAMANI", "DYAKA", "FORKOR", "GBENA", "GBENTIE", "GBEO", "GRUMO", "GUOR", "GYMMALI", "HACKEY",
        "HALITU", "IMORO", "ISSAHAKU", "ISSAHAQUE", "JANALE", "KAABO", "KALVEI", "KAMBAYIRE", "KAMEN-YI", "KANTON",
        "KARIMU", "KELLE", "KONG-YE", "KONTEGE", "KPENUOR", "KULLAH", "KUMIL", "KUNKAA", "KUNLANGPUURI", "KURI",
        "KUUBALIERE", "KUUKYAARA", "KUUSORING", "KUUTAPAGRA", "KUUYUOR", "LABANTI", "LAMBOH", "LANDOR", "LOOZIE",
        "MAALE", "MAHAMA", "MASAWUDU", "MAAWERE", "MOHAMED", "MUMUNI", "MWINE", "NAAB", "NAAEDER", "NAANGMENVELAA",
        "NABUNA", "NAGUO", "NAMILAH", "NANkAANYE", "NANPUSUORE", "NAPAABA", "NAPO", "NARIBONG", "NASARE", "N-DERA",
        "NELE", "NGMENAAYELLE", "NGMENAPUO", "NGMENBABANGNA", "NGMENLAARA", "NGMENEPUO", "NINGDOONAA", "NONG",
        "NONGNEGE", "NUORTUO", "NYASU", "NYONFO", "OSUMAN", "PENGNYINE", "PIITANG", "POGNIZUMAH", "PUOBANYERE",
        "PUONGSO", "PUSO", "SAALE", "SAAZIE", "SABULI", "SAGNIZU", "SALIFU", "SANSAH", "SAWALE", "SEIDU", "SINKARI",
        "SINKARE", "SOFAAR", "SOMI", "SORJIA", "SUBONNE", "SUGLO", "SULLEY", "SUNKPAL", "SUUGYA", "TAABAPUO",
        "TABORMAH", "TAHIRU", "TANG", "TANGBILE", "TAPONG", "TENGAN", "TENSAANAA", "TIEONAAH", "TIERE-YAGA",
        "TIGBORO", "TONO", "TUOLAANUO", "TUOLIENUO", "UMAR", "UUBAR", "WAJIWIE", "WIYORBIE", "WUWIE", "YAAKUU",
        "YAAMUO", "YAAO", "YELDZIA", "YENGE", "YIBONG", "YIIRU", "YIMIAH", "YIRDEBR", "YUORMWAA", "ZEIDU",
        "ZIMBELLE", "ZONGO", "ZUBEE", "ZUURI", "AAYANGDONG", "ABASS", "ABDULAI", "ABDUL-RAHIM", "ABDUL-WAHABU",
        "ABOTILUM", "ABU", "ABUBAKAR", "ABUBAKARI", "ACHIM", "ADAMS", "ALIDU", "AMINU", "ANGBANYE", "ANGBINGZU",
        "ANGDENNE", "ANGKPARA", "ANGNONOBA", "ANGWELLE", "ANKOKPI", "ANSOKPIEO", "ANTELE", "ARAH", "AYIKORONG",
        "BAAGULIBE", "BAAMONBEE", "BAATAH", "BABASORONAA", "BABAWONOSORO", "BABELENYEH", "BABOORONONE", "BACHAN",
        "BACHANG", "BAFAASEH", "BAFRE", "BAGYIL", "BAGUULIBE", "BAKIRIN", "BAKURO", "BAKUSER", "BAKYEE", "BALIGYA",
        "BALISIN", "BALOO", "BALORO", "BAMUOH", "BANATTEASE", "BANITAKIA", "BANKWA", "BANU", "BANUBIE", "BAPULA",
        "BAREFAARE", "BASINBENSOR", "BATIA", "BATONG", "BATUU", "BATUUROBAL", "BAUUNO", "BAWANGMA", "BAYENDEME",
        "BAYEOU", "BAYUKE", "BEYUO", "BAZINENAA", "BAZURAH", "BE-APUO", "BEBU", "BEENE", "BELBAAR", "BELLE",
        "BERAAWULA", "BERMUOH", "BESAM", "BESOGLE", "BEZEGR", "BILLEH", "BILLEY", "BODI", "BODONG", "BOLLU",
        "BOMBANYE", "BOMBEFAA", "BOMMIE", "BONGKANSAA", "BONGTARA", "BONLE-IB", "BONNIR", "BOODARI", "BOODOMO",
        "BOOFAAR", "BUCHAGE", "BUDUA", "BUKARI", "BULELE", "BUNWERE", "BUORODIRE", "BUOSENGTAA", "BURE", "BUREENAA",
        "BUROH", "SAADAARE", "CHEBE", "CHESU", "CHIRAA", "CHOOMUO", "CHUON", "DAA", "KAAFAA", "DAARA", "DABUO",
        "HADDI", "DAKPIRI", "DANAA", "DANBO", "DANGMAA", "DANSAANA", "DANYI", "DANYIR", "DAUDA", "DE-AZAA", "DEBUO",
        "DENDEE", "DIIWU", "DINDORI", "DIYUO", "DOBARA", "DOGEKUU", "DOMEBALE", "DOMMEBEDEO", "DOMO", "DOMOH",
        "DOMOPULING", "DOMOTIERE", "DONBELOUN", "DONGBE-INAA", "DONGBINE", "DONGYAAE", "DONG-YAG", "DONNIYONG",
        "DONYIRI", "DOOBAARE", "DOOSOGLAA", "DORDAA", "DORDAH", "ROLAND", "DOUNPUNG", "DUNEEBONG", "DUO",
        "DUWIEJUA", "EMBANGA", "ENIE", "ERESONG", "FAADAAR", "FAA-OB", "FAATAH", "FOBVOI", "GAAMAAL", "GAANYE",
        "GANDAA", "GARIBA", "GARIBU", "GBAL", "GBARE", "GBARENAA", "GBEDAA", "GBELEZIE", "GBANA", "GIRO", "GODFRED",
        "GOMINA", "GYEBARE", "GYELLE", "GYENGYERE", "GYUULAH", "HAMIDU", "HARUNA", "ISSAH", "JAHTO", "KAABE",
        "KAAKPEMA", "KAARAYELLE", "KAATUO", "KABIRI", "KAKUUNAANI", "KALIEBO", "KANDOH", "KANTAYENG", "KANJUA",
        "KANTAKPE", "KANTASU", "KAPERE", "KAUKANSORO", "KAZIE", "KENNEE", "KOFINAA", "DONKOR", "KONKURI", "KONLEE",
        "KONTADAA", "KOORONYUURO", "KPERE", "KPIN", "KPINTAATOBO", "KPOKO", "KPOKPORI", "KUFONG", "KULAH", "KUNEI",
        "KUNSAALARE", "KUNTULO", "KUUBAAR", "KUUBABERE", "KUUBE-ERE", "KUUBILE", "KUUDEGR", "KUU-IRE", "KUUKA",
        "KUUNAA-ERE", "KUUNAGAAYENG", "KUUNAVENG", "KUUPAALA", "KUUPOL", "KUURIDONG", "KUUSANNUO", "KUUTAMIINE",
        "KYIEYI", "KYIZAGL", "KANGYOR", "LIEKO-DARI", "LIEKOZONG", "LIEWANA", "LURI", "MAA-IRE-FAAR", "MAAL-IRE",
        "MAJEED", "MAJIIDU", "MATHIAS", "MENSAH", "MILNYOG", "MINEBONG", "MOHAMMED", "MUHAMMED", "MUAH", "MUSAH",
        "MWIN", "MWINBAM", "NAA", "NAABA", "NAABEH", "NAABEPIGRE", "NAAMWINKPENG", "NAMPUSUORI", "NAAKULE",
        "NAAWONETUO", "NAAZIE", "NAAZUING", "NABOME", "NAMBONNO", "NANKENMIE", "NANKPA", "NAPAALA", "NATUO",
        "NAWURI", "NENFAASIE", "NGMENGAA", "NGMENLANAA", "NGMENSOA", "NIBENEE", "GBAARAH", "NINANGZIE",
        "NINFAASOAYIRI", "NIRKANG", "NOBALAYIRI", "NOKPIEN", "N-PUNIA", "NUOBE", "NUZAGLAA", "NWIININ", "NYIARU",
        "BRIGHT", "PAALEE", "PAALO", "PENNE", "PENGMAAH", "PENNEH", "PIELONGDONG", "PINGNAA", "PIRIPUO", "POGBAAR",
        "PUO", "PUODEGEE", "KANGSANGBATA", "RAZAK", "SAANDAARE", "SAA-EEBO", "SAMANI", "SAMWINI", "SAAWIE", "SENTI",
        "SIYIRPA", "SONGLAYENG", "SULEMANA", "SULEMANI", "SUMAILA", "SUMANI", "SOUPUO", "TAABANYUURI", "TAABO",
        "TABO", "TAKOR", "TAMPELLU", "TANGZONG", "TATI", "TENG-IB", "TENGSAA", "TERSUURI", "TIERTO", "TOBIE",
        "TAPULEE", "TUOBEDAARE", "TUONAA", "TUUBERE", "VENKUMWINE", "VENU", "VUUDIKUBO", "VUURU", "WANYE", "WIMINA",
        "WIRIBARE", "WONGTO", "YANKONO", "YELDEBONG", "YELPAALA", "YELPUO", "YENG", "YENGBAWULLO", "YIPAALA",
        "YIRMELE", "YITUORI", "YUONI", "YUSSIF", "ZAGRIBER", "ZEMONG", "ZIEKYE", "ZIEM", "ZINEKUU", "ZINTIERE",
        "ZONISUUR", "ZOLKO-ERE", "ZULEE", "ZUMANIE", "ZUMAYELLE", "ZUOTO", "AABESAGR", "AABIER", "TUORANIE",
        "AAKYE", "AAYARE", "ABAADEMAH", "ABDUL", "ABUOKANBANG", "ABUORO", "ALAZUMAH", "ALI", "AMADU-ANTINWII",
        "AMOSSAH", "AN-CHOSUMMO", "ANG-BAL", "ANGLAAMWIN", "ANGNONOMA", "ANGSOROBAALA", "ANGSEOH", "ANWELLE",
        "ARATUO", "AWUDU", "AZAASOMA", "BAADEA", "BA-AROO", "BAATEKUU", "BAAWUO", "BABA", "BACHOLLOR", "BAGYILIKO",
        "BAHAARA", "BAKWIE", "BALAARA", "BALIERETREH", "KABIO", "BAMWINAA", "BANAANGMEN", "BANGNEWEB", "BANIE",
        "BANUURO", "BANYENDEME", "BARA", "BATIENU", "BATUSING", "BAVIAH", "BAVOKA", "BAWAARE", "BAYAAYELE",
        "BAYELLEBARA", "BAYOUR", "BAZAAWAALE", "BEBURE", "BE-IRNIBE", "BELKO", "BEPULE", "BESANGN", "BETUUR",
        "BIBORAH", "BILLE", "BINAH", "BODORMA", "BONGBAL", "BONGNEA", "BONIYEL", "BONSING", "BONTAREBA",
        "BOOWATOGRO", "BORI", "BORSU", "BUKU", "BULUBAYONG", "BUNUZUING", "BUNYORU", "CHAKILITUO", "CHARLES",
        "CHARLOTTE", "DABAALA", "DABAYA", "DAGBIE", "DANGMAAH", "DANIKUU", "DANKATIE", "DANUO", "DASAAH",
        "DEKOMWIN", "DELLE", "DENDEN", "DERBIER", "DIAKANWI", "DIATUO", "DIBAARENYERE", "DIEYELE", "DINAA", "DOMA",
        "DOMATIERE", "DOMOKYEBE", "DOMOLAMPULING", "DOMONINGE", "DONKERE", "DOONYUORI", "DOOSAAH", "DARIGINA",
        "DORLAYIRI", "DORZAGLA", "DOUCHEBE", "ELEDI", "EPIREH", "EREDOGLO", "EUYI", "FAARA", "FAJIN", "FERUTAE",
        "FIELE", "FONGNAA", "GAAYUONI", "GALMAH", "GBAARA", "YIRIYELE", "GBANG", "GBEMMIE", "GBEZIE", "GBIREH",
        "GEMAH", "GUGUO", "GYIMAALE", "HAABONG", "HAMAJAN", "IBRAHIM", "JAMALDEEN", "JOKI", "KAAPUL", "KALIBIE",
        "KAMBA-ENIE", "KANBIAU", "KANDOMO", "KANGTAAZIE", "KANSOH", "KANDEH", "KARIM", "KATUO", "KOGLIYIRI", "KOH",
        "KPAN", "KPEGYLEYIR", "KPIEPAALAA", "KPIINZIE", "KUUBASEU-UM", "KUUBEKYERE", "KUUBONG-DERI", "KUUGBEPUO",
        "KUU-IM", "KUU-INLE", "KUUKYERE", "KUUNAYIRE", "KUUGYANG", "KUUZUENG", "KYEKPIEO", "KYEVOUN", "LAMUOH",
        "LANDON", "LATIF", "LEBENETEY", "LEER", "MAALU", "MAAMUDU", "MAANIAFAA", "MAMURU", "MINU", "MONYUU",
        "MOOMIN", "MUO", "NAABI", "NAA-ER", "NAA-IBONU", "NAALAH", "NAAMWINNINGE", "NAANGMEN-IRE", "NAANGMEN-NUURI",
        "NAANIBE", "NABOMA", "NABINA", "NAGBORI", "NAMAAL", "NANG", "NANGLATUO", "NANGNIE", "NASAAL", "NASIGIBE",
        "NASONG", "NAWIA", "NEETEGE", "NGMENSOMMA", "NGMAAN", "NGMENKAARA", "NGMENTIERE", "NGMEYANG",
        "NINFAA-KULLAH", "NINLE", "NINTAANYOORI", "NKPENYIN", "N-PEI", "N-TIEREBONG", "NUBAZIE", "NUOKPAH",
        "SUTULO", "NUOWE", "N-YELDEBONG", "N-YELKO-ANG", "POLAA", "PORINBU", "POTIERU", "PUOTUO", "SAAYENG",
        "SALIA", "SAMPEI", "SANDOR", "SA-URI", "SAWARI", "SIAFAH", "SIGNA", "SOBARI", "SO-ENGA", "SOKUU", "STEPHEN",
        "SULE", "TAAKAWE", "TAALIKI", "TADI", "TADITUO", "TAHII", "TAMPOE", "TAMPUORI", "TAFSIRU", "TEDURI",
        "TENGSO", "TENSARI", "TIE", "TIEREKUU", "TIERO", "TONIA", "TORNIA", "TUNYINE", "TUOPARE", "TURIBARE",
        "WAFONG", "WIBOMOR", "WIENAA", "WUO", "WUOGBEEKULI", "DUOPARE", "YEB", "YELBE-IRE", "YELYEN", "YENLY",
        "YIFAA", "YIIBI", "YIR-ERU", "YUONSUNG", "ZAAVIEL", "ZAMBO", "ZORNAA", "ZUBATOGRO", "ZUYELLE", "ZUZIE",
        "NASSIM", "MENDIENYE", "DALUGO", "NGMEN-YELLE", "BAPARIMA", "BOAH", "SONGLIEDONG", "KPOKPOLAA", "BADUNG",
        "AALAAREKUU", "KUGBIE", "BIEPKE", "FUESINI", "LANIDUNE", "ABDUL-RAHAMAN", "AZIZ", "BALBAARE", "BENNI",
        "NAAMWINKUM", "BA-ERENYUURI", "SAAKA", "ANGNUURING", "NIBEPUO", "KUUBATAAZIE", "GBIEO", "SOGLEE", "BOSORO",
        "DATIEKA", "BAADEKUURI", "ANGUYIRI", "NABURI", "KUUYELLE", "BONGA-PARE", "ANGSUMA", "ANSUORO", "DAARU",
        "NYUOR", "SOFAARE", "BAKIMO", "BAKPADIA", "KPARE", "BAMINGEKABA-IRE", "WUBONTO", "FUSEINI", "ANATAKANG",
        "BA-IREBARE", "ZUSOGLA", "SOMIRETEY", "TENLIE", "LEY", "BEKYAALAAR", "DOMOBOLEE", "KPIEOBAARE",
        "BAALAYELLE", "GAABONZIE", "BAKIRIM", "DERY-NAABAA", "BOZAGLA", "BAWADE", "BASOORO", "NYOGMA", "NUOBALE",
        "ZINGUAKUU", "DAMSER", "TENFUL", "ZIEME", "KANBONGYEL", "TUUROYENG", "TUOBENYIER", "DANGNIKUU", "KOKORO",
        "NAAZELLE", "ZU", "DAGBIELE", "GUBA", "KUUBOORE", "KAVUA", "ABDUL-HAMID", "ZON", "KANTUWOLA", "BAYORBOR",
        "NIBENANG", "ZAAGBEB", "DINMIE", "FORKAH", "FIRUZIE", "WULLO", "KANZONGMEN", "MAMURI", "KPIFONG", "DASAA",
        "BONGNO", "NUAGAH", "BANONO", "BA-EFAAH", "NGMENYAAO", "BAPITIE", "KOMIRI", "KENEE", "KOGRI", "KAAPUORI",
        "BUNYE", "JAANITII", "BAGONLURI", "NGMENGENG", "SUONE", "ANLABONG", "GHANDI", "NINFAAZUMA", "BOKUNOBO",
        "DONGYAA", "BASINGE", "ENBAWAABA", "BOOLANPUO", "ATALUA", "BAMBAARE", "KOGI", "DOMOYEL", "ZUBERU",
        "YIRIYUOR", "MAAMBO", "NAAMO", "BARRY", "ABUDU", "TIMOTHY", "AABELLE", "KABIR", "BE-IR", "DANAAH",
        "KUU-ERINUURI", "INUSAH", "BAGYIRI", "SONIBO", "GANDI", "SOBONG", "LAASO", "ZAATO", "KPINITUO", "LILIBE",
        "FAALU", "KUUVENLE", "PIITO", "ZINGBONG", "BASOGLOYELE", "NONNO-IRE", "DOGBER", "MAANIBE", "SANSAARE",
        "IDDRISU", "TENNOH", "FUDALI", "DONGSEOTAA", "YANGBEDAAR", "AAGYEREDOGFO", "TIERUNG", "LAARI",
        "DERNYANGDER", "TANTIE", "YAHAYA", "KOMUOH", "KURE", "YUNUS", "SORI", "VAAH", "AMAKAYOR", "SOMBO",
        "ANGKYIIRENAA", "KAYIRIZELLE", "DORSAH", "OSMAN", "YANG-MAADOME", "NIBEZUING", "CHARDERETEY", "KUU-IRENUBA",
        "MENDINYE", "NAASENUOR", "DAUD", "DONNEYONG", "BAHAADOMO", "KUUYORU", "BAWAWUNG", "BAADEYIRI",
        "DOMOBEPULING", "BALARA", "GAM", "WULAKOO-ERE", "GUOBERU", "BATUO", "BOROH", "WONITOR", "YENDEMU",
        "BULUUTEY", "KYAAVUURDON", "MENNOMBAARE", "BARIMINIA", "ADAMU", "TIGMEH", "BASI", "NAAWULLE", "TIEOZIE",
        "AMPULING", "TUKPEH", "GBELLU", "NASAALAZUING", "DAKONO", "DIPORO", "ZIGNYE-EE", "FAANUBANYE", "DOHO",
        "NOBANAA", "BAKOBIE", "PUOZUING", "BOORE", "GYIELE", "KAABATA", "ABDUL-SALAM", "MAALA", "MAALISAA",
        "KUUMUULO", "TUU", "SAADIE", "DELE", "KAALIWADII", "BOOLUPUO", "PUKYIIRI", "PENKAAWE", "KOGLE", "NURAKA",
        "BIBIO", "MOGTARI", "TENI", "SAAMWAA", "KANSANGBATA", "BUOBO", "SAADONG", "BAALONG", "BATAA", "NAJIRIWIE",
        "BOKUOR", "BOUR-IB", "ELYASU", "ANGLIIRE", "KPIEOLABONG", "KANNYOGE", "DAUDI", "WASAH", "KONDAA", "GENGNE",
        "BASING", "BADEPONG", "MWINBONG", "MORO", "DIEYEL", "KUUTUO", "YIKYIL", "AABETIEREKUU", "AANYE", "AATIE",
        "AAVENEKUU", "ABAKOORO", "ABDUL-HAKI", "ABOBO", "AHIME", "ALPHA", "AMADU", "ANGLAANIE", "ANGSO",
        "ANGSOKPIEO", "AREGOMA", "AWILBA", "BAALAZOE", "BA", "BAARIKOH", "BABAUUNO", "BABAZELLEYIRI", "BABILOLLO",
        "BACHO", "BADAKIA", "BADIKO", "BADOMMIE", "BADOUMIE", "BAFAANYE", "BAFAKANA", "BAFERE", "BATUNA", "BAGBULO",
        "BAGOG", "BAJUASU", "BAKU", "BAKUWIE", "BALANG", "BALANGNA", "BALANKO", "BALBULEE", "BALLO", "BANYOGKU",
        "BASAANADERI", "BASAMA", "BASINMIE", "BASUGLO", "BA-URO", "BAYELZINE", "BEKYOGRE", "BENNE", "BOGKUR",
        "BOGRI", "BOMBA-IRE", "BONBIMMO", "BONGSING", "BONNIKUU", "BO-OGRO", "BOORI", "BOOSORO", "BOOWULA",
        "BOOWURO", "BUGU", "DAABIE", "DAKURIPE", "DAKUU", "DAMAARONG", "DANANG", "DANTUOR", "DASSAH", "ELEBANG",
        "ERE-KA-I-NUO", "FERE", "GALAA", "GBALA", "GUNUURI", "GURI", "GYABIL", "GYIREH", "IMORU", "ISSAKA",
        "JAKALIA", "JANFARI", "KADIRI", "KANGPOG", "KANGSAABONG", "KANTA", "KANTIEHEBIO", "KANTIEREFAA", "KANYOR",
        "KASIM", "KATARA", "KAFOOMENLA", "KOMAH", "KONKPIER", "KONTUOLIE", "KORLGNU", "KPEBDAAR", "KPEDE",
        "KPEDEYI", "KPENU", "KULINYE", "KUUKANONO", "KUULAFAA", "KUUMOLE", "KUUNIBE", "KUUPOLU", "KUUSEG", "KUUSIE",
        "KUUSONNE", "KUUSORO", "KUUWELLEYIR", "KUUWIE", "KYE-UMBO", "LABAAR", "MAABO", "MAAKAKPIER", "MONYE",
        "MURAH", "MUSTAPHA", "MWINBOM", "MWINGYINE", "NAADAAR", "NAAMWINKUU", "NAASAALAATOMA", "NADOLI", "NAGA",
        "NALA", "NAMAALLAH", "NANGBONG-ZENI", "NASIGEBE", "NINDOONAA", "NINFAANUORI", "NINNONI", "NOBALANAA",
        "NUHU", "NUUDONG", "NYAAKPIN", "NYUORI", "NYUWIRE", "N-ZUYEL", "PIANTEY", "PUOBAGBIRE", "PUO-ERU", "SAKANG",
        "SAMPAALA", "SAMSON", "SANDAARE", "SANGNA", "SAURI", "SEG-IRU", "SEG-YELLU", "SEREYI", "SEY", "SIENE",
        "SIINAYOR", "SIN-ENOU", "SOBITEY", "SOGME", "SONGKURA", "SONO", "SOTUO", "SOYIE", "SUURBAAR", "TABONG",
        "TANGBER", "TENGENABANG", "TERKUU", "TERSER", "TETTEH", "TIERETAA", "TINDAA", "TI-YANG", "TIZAAKANA",
        "TOOBIN", "TUKPE", "TUOKABALAARA", "TUOKYEM", "TURIKO", "VUURI", "VOBAKAAWONO", "WOME", "YANGBAAR",
        "YELEWULLA", "YELPAABA", "YENDOR", "YENGDEME", "YENGKAAYI", "YIRWEL", "YIYUGSAH", "YUOSUNG", "ZAAFII",
        "ZAAGUORO", "ZAKARIA", "ZENENYAABO", "ZURE", "ZUOLO", "ZUSAGLA", "AMEYAW", "DISUURI", "DOGKUTENGE",
        "DONGKARA", "DONGUDURO", "DOMOYIE", "DIFAA", "BANGMENAA", "DOMALABUO", "KUMBAAH", "DUUL", "DOOHWIERE",
        "DATIAKA", "NGMENSUNGEE", "DONDOYEL", "KAZINENAA", "DOOH", "ERBONTEY", "SIBINA", "DON-YI", "SEGKUU",
        "NUOLAYENG", "GUOLIDOMO", "WALBOMA", "DOONYUO", "KOG", "SAKAI", "N-PUOYEL", "BELLINGSER", "BAMPUO",
        "BAWADARI", "KONG-YEL", "EBONG", "DEMEKPEE", "DONGYAGA", "ZUUR", "BABAMIINEKUU", "AKURAH", "NINBENYEL",
        "ANGKPEREKOO", "KPINKO", "NINTAANYOORE", "DUMBU", "BABANG-AYENG", "KABURU", "DOOSAA", "ANGWERENGEN",
        "KYEREE", "DOOZUOH", "ZURY", "BEGUBRE", "HAANAA", "MANKUNA", "AABANGNAA", "AMBRA", "ATANGA", "BAALASUURI",
        "BABA-UUNO", "BADONG", "BAHAAKPEME", "BALLU", "BANIERE", "BATASOORE", "BAYOGLE", "BONKANG", "BOOR",
        "CHUNTON", "GBANHA", "KPESI", "KUBIO", "KULA", "NAAMWANURU", "SAAKABO", "SAAKU", "SIBIRI", "SIDIKI",
        "SINTIA", "YER", "WUOYANG", "WAKANMAWIA", "UUFOTUO", "TOMEH", "TANYE", "TAA-ENURING", "AHIMODU", "ANDOONO",
        "ANG-ERE", "ANSUMAH", "ASIERE", "ATTO", "AYARIKA", "BABULWERI", "BABUNA", "BADENYE", "BANYIGE",
        "BETUGNYIGE", "BOGNE", "DAGBEE", "DAVORA", "DEPULLA", "DIEKUU", "EREPUOR", "KANDATAM", "KUUBATAASUURI",
        "KUUBURO", "KYIIR", "LANGBONGMENAA", "MAABOBRA", "MAALE-ENG", "MWINBELLE", "NGMENZU", "PUURIBALANGTAA",
        "SAABLA", "SAMBA", "SANG-ALA", "SANGMENE", "SO-OB", "SOZIE", "SUAT", "TAMPAAL", "TANBIIR", "TIEWUL",
        "TOMMUA", "WIEFAA", "WULAPARITUO", "YENGBAAREE", "YIRKPENG", "YIRYUGSAH", "BABATEGRE", "BAGR", "BAGUULO",
        "BANGNIA", "BEPAGR", "BONKYERI", "BUNTUOLUU", "DAGBALE", "DANZENE", "DA-URE", "DIENYUURI", "DIGRE",
        "ENENG-BONG", "GBIEL", "GOBAA", "KABE", "KAMWINWANYE", "MOGTAR", "MWINZUME", "NAAMOGTAN", "NAAWAE",
        "NABOMEH", "NGMENAA", "NINGEVIELLE", "NOPIEL", "NYONYOH", "PULI", "SAABEKA", "TAAFAALE", "TECHIRE",
        "TUOKPIER", "VUODER", "YIRYELE", "ZUBANYUURO", "TAGTIR", "KUUPARE", "LIGRE", "ABAWIERE", "ANGSOZIE",
        "ATIAH", "AYINE", "AZAAKANBE", "BAAPOGMA", "BADIEL", "BAKUPOGE", "BASOMASAL", "BAYULEE", "BAATIE",
        "BORTEGRE", "DANGUNMEH", "DANYAGRE", "DEKORE", "DERRY", "DOGU", "DONGYENG", "DOOZIE", "GUNIZOA", "HAKIM",
        "KPIKYEYUOR", "KUNVENGSERE", "KWABENA", "MWIN-NYAO", "MWINELARE", "NABIRI", "NIBEEN-YEL", "NOKONI", "PIWIE",
        "SAAYEG", "SOGRAAMWINE", "VIELU", "YAGABAARE", "ZAA", "BAKPAALA", "BAREGOMO", "BATI", "BELLEDONG",
        "BILINKPE", "CHONYENEH", "DOGNAA", "DOMOBALEE", "DONGNIKONG", "DOOKUURI", "DUOYER", "GOGOO", "GOMA", "KALI",
        "KANBONYEL", "KATAAH", "KONTIERU", "KPONKPOL", "KUPAH", "KYEBR", "MAYIR", "NANSIE", "NINDOR", "NSOGLENYIN",
        "NYEMMAWERO", "NYINA"
    };


    public static List<string> Names { get; } = new List<string>
    {
        "Susan",
        "Christine",
        "Margaret",
        "Judith",
        "Jennifer",
        "Karen",
        "Patricia",
        "Mary",
        "Linda",
        "Barbara",
        "Elizabeth",
        "Robyn",
        "Wendy",
        "Helen",
        "Heather",
        "Lynette",
        "Anne",
        "Sandra",
        "Diane",
        "Carol",
        "Pamela",
        "Janice",
        "Janet",
        "Suzanne",
        "Raewyn",
        "Sharon",
        "Dianne",
        "Julie",
        "Rosemary",
        "Deborah",
        "Pauline",
        "Alison",
        "Kathleen",
        "Denise",
        "Lorraine",
        "Catherine",
        "Yvonne",
        "Marie",
        "Ann",
        "Beverley",
        "Lesley",
        "Shirley",
        "Colleen",
        "Annette",
        "Marilyn",
        "Maureen",
        "Glenda",
        "Jane",
        "Jillian",
        "Sheryl",
        "Gail",
        "Lynda",
        "Brenda",
        "Jacqueline",
        "Kay",
        "Carolyn",
        "Marion",
        "Maria",
        "Cheryl",
        "Donna",
        "Kathryn",
        "Vicki",
        "Jeanette",
        "Jan",
        "Gillian",
        "Sally",
        "Ruth",
        "Lynne",
        "Jocelyn",
        "Jill",
        "Joanne",
        "Maree",
        "Frances",
        "Valerie",
        "Elaine",
        "Dorothy",
        "Glenys",
        "Shona",
        "Adrienne",
        "Irene",
        "Joy",
        "Angela",
        "Lois",
        "Paula",
        "Vivienne",
        "Bronwyn",
        "Fiona",
        "Louise",
        "Stephanie",
        "Debra",
        "Christina",
        "Ngaire",
        "Jean",
        "Diana",
        "Claire",
        "Lynnette",
        "Joan",
        "Penelope",
        "Gloria",
        "Katherine",
        "John",
        "David",
        "Peter",
        "Michael",
        "Robert",
        "Paul",
        "Stephen",
        "Kevin",
        "Christopher",
        "Brian",
        "William",
        "Ian",
        "Mark",
        "Richard",
        "Alan",
        "Bruce",
        "Murray",
        "Graeme",
        "Wayne",
        "James",
        "Gary",
        "Anthony",
        "Graham",
        "Philip",
        "Barry",
        "Colin",
        "Trevor",
        "Kenneth",
        "Ross",
        "Grant",
        "Geoffrey",
        "Raymond",
        "Keith",
        "Allan",
        "Donald",
        "Ronald",
        "Roger",
        "Steven",
        "Gregory",
        "Neil",
        "Andrew",
        "Warren",
        "Garry",
        "Russell",
        "Thomas",
        "Dennis",
        "Phillip",
        "Stuart",
        "Douglas",
        "George",
        "Robin",
        "Leslie",
        "Malcolm",
        "Gordon",
        "Edward",
        "Neville",
        "Terence",
        "Martin",
        "Charles",
        "Patrick",
        "Timothy",
        "Lindsay",
        "Noel",
        "Rex",
        "Kerry",
        "Joseph",
        "Brent",
        "Craig",
        "Jeffrey",
        "Gavin",
        "Rodney",
        "Nigel",
        "Alexander",
        "Bryan",
        "Owen",
        "Tony",
        "Eric",
        "Lawrence",
        "Glenn",
        "Arthur",
        "Bernard",
        "Denis",
        "Ivan",
        "Francis",
        "Mervyn",
        "Henry",
        "Gerard",
        "Norman",
        "Derek",
        "Desmond",
        "Simon",
        "Maurice",
        "Nicholas",
        "Lance",
        "Brett",
        "Daniel",
        "Frederick",
        "Roy",
        "Stewart",
        "Kelvin"
    };
}